version: '3'
services:
  mysqldb:
    gamelogic_db: mysql:5.7
    container_name: gamelogic_db
    ports:
      - "3306:3306"
        environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: root
        #MYSQL_PASSWORD: password
        MYSQL_DATABASE: tribes_db
    volumes:
        - mysql_gamelogic_db:/var/lib/mysql/

    mysql_battle_db:
    image: mysql:5.7
    container_name: battle_db
    ports:
      - "3306:3306"
        environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: root
        #MYSQL_PASSWORD: password
        MYSQL_DATABASE: battle_db
    volumes:
        - mysql_battle_db:/var/lib/mysql/
    
    mysql_player_db:
    image: mysql:5.7
    container_name: player_db
    ports:
      - "3306:3306"
        environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: root
        #MYSQL_PASSWORD: password
        MYSQL_DATABASE: player_db
    volumes:
        - mysql_player_db:/var/lib/mysql/
        
        
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    container_name: ngnix
    image: nginx:latest
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/conf.d:/etc/nginx/conf.d
      - /opt/www:/opt/www

    ports:
      - "80:80"
      
  auth-server:
    container_name: auth-server
    image: auth-server:latest
    ports:
      - "9100:9100"

  eureka-server:
    container_name: eureka-server
    image: eureka-server:latest
    ports:
      - "8761:8761"

  zuul-gateway:
    container_name: zuul-gateway
    image: zuul-gateway:latest
    ports:
      - "8762:8762"

  message-service:
    container_name: message-service
    image: message-service:latest
    ports:
      - "9300:9300"
      
  battle-service:
    container_name: battle-service
    image: message-service:latest
    ports:
      - "9301:9301"
      
  game-service:
    container_name: game-service
    image: game-service:latest
    ports:
      - "8080:8080"

  player-service:
    container_name: player-service:
    image: player-service::latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8401:8401"
      - "8400:8400"
volumes:
    mysql_player_db:
    mysql_battle_db:
    mysql_gamelogic_db:
      
